manifest:
  remotes:
    - name: aspeed
      url-base: https://github.com/AspeedTech-BMC

  # Please add items below based on alphabetical order.
  # These dependencies may need updating if new features are added to the firmware.
  projects:
    - name: zephyr
      remote: aspeed
      path: zephyr
      revision: db3dbcc9c52e67a47180890ac938ed380b33f91c
      import: 
        name-allowlist:
          - cmsis
          - mcuboot

  self:
    path: openbic

